kind: pipeline:
name: default

steps:
  - name: buildiso
    image: yonggan/manjaro-buildiso
    commands:
      - mkdir -p ~/manjaro-tools
      - echo "run_dir=/drone/src" > ~/manjaro-tools/iso-profiles.conf
      - buildiso -p kde-whitesur-dark -v
    
